guru:
  jms:
    username: JMS Username
    password: somepass
    url: SomeUrl

ignore_new_lines: >
  this is
  just one long
  string

include_new_lines: |
  asdf asdf asdf
  asdf adfewf asdf
  asdf ae adfre